use college;
select * from lokesh;
CREATE USER 'user1'@'localhost' IDENTIFIED BY '1234';
select * from lokesh;
GRANT SELECT, INSERT ON college.lokesh to 'user1'@'localhost';
FLUSH PRIVILEGES;
SELECT user, host FROM mysql.user;
SHOW GRANTS FOR 'user1'@'localhost';
CREATE USER 'navya'@'localhost' IDENTIFIED BY '4444';
SELECT user, host FROM mysql.user;
GRANT SELECT, INSERT ON college.lokesh to 'navya'@'localhost';
SHOW GRANTS FOR 'navya'@'localhost';
FLUSH PRIVILEGES;
REVOKE INSERT ON college.lokesh FROM 'user1'@'localhost';
SHOW GRANTS FOR 'user1'@'localhost';
REVOKE select ON college.lokesh FROM 'user1'@'localhost';
SHOW GRANTS FOR 'user1'@'localhost';
DROP USER 'user1'@'localhost';
SELECT user, host FROM mysql.user;